name: Terraform Plan Validation

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Terraform Static Analysis"]
    types:
      - completed

jobs:
  Terraform-Staging-Plan-Validation:
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Determine Environment & TFVARS File Based On Branch That Static Analsis Ran On - Workflow Dispatch
      - name: Determine Environment
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            BRANCH="${{ github.ref_name }}"
          else
            BRANCH="${{ github.event.workflow_run.head_branch }}"
          fi

          case "$BRANCH" in
            dev)
              ENV="dev"
              ;;
            staging)
              ENV="staging"
              ;;
            main)
              ENV="production"
              ;;
            *)
              echo "Invalid Target Branch: $BRANCH"
              exit 1
              ;;
          esac

          echo "ENV=$ENV" >> $GITHUB_ENV
          echo "TFVARS_FILE=environments/${ENV}/${ENV}.tfvars" >> $GITHUB_ENV
          echo "Using TFVARS File: environments/${ENV}/${ENV}.tfvars"

      # Confirm TFVARS exists
      - name: Confirm TFVARS File
        run: |
          if [ ! -f "${{ env.TFVARS_FILE }}" ]; then
            echo "Unable To Find: ${{ env.TFVARS_FILE }}"
            exit 1
          fi
          echo "Found: ${{ env.TFVARS_FILE }}"

      # Clear Cahce
      - name: Clear Cache
        run: |
          echo "Cleaning Cache..."

          rm -rf .terraform
          rm -f .terraform.lock.hcl

          rm -rf environments/${ENV}/.terraform
          rm -f environments/${ENV}/.terraform.lock.hcl

          echo "Cleanup Complete"

      # Remove Backend Block File
      - name: Remove Backend.tf
        run: |
          rm -f backend.tf
          echo "Backend.tf Removed Successfully"

      # List Modules
      - name: List Module Folders
        run: ls -l Modules/

      # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # TF Version
      - name: Terraform Version
        working-directory: .
        run: terraform version

      # Terraform Init
      - name: Initialize Terraform
        working-directory: .
        run: terraform init -backend=false -var-file=${ENV}.tfvars

      # Terraform Version
      - name: Terraform Version
        working-directory: .
        run: terraform version

      # Terraform Plan
      - name: Terraform Staging Plan
        run: |
          terraform plan \
            -var-file="environments/${ENV}/${ENV}.tfvars" \
            -var="ssh_public_key_path=${{ secrets.VMSS_SSH_PUBLIC_KEY }}" \
            -out=tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
